[project]
name = "parlant-reproduce"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ollama>=0.5.3",
    "parlant==3.0.2",
    "python-dotenv>=1.1.1",
]
